version: '3'

services:

  test-db:
    image: 'mysql'
    container_name: 'test-db'
    environment:
      - 'MYSQL_ROOT_PASSWORD=1111'
    volumes:
      - './test-db:/var/lib/mysql'

  test-api:
    image: 'omisoft/sb-hotels-reservations'
    container_name: 'test-api'
    depends_on:
      - 'test-db'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://test-db:3306/hotels?createDatabaseIfNotExist=true'
    restart: 'on-failure'
